name: manual
on: [workflow_dispatch]

env:
  VALUE: "foo"

jobs:
  manual:
    runs-on: ubuntu-latest
    name: Testing conditional env
    steps:
      - name: Echo ref
        run: echo ${{github.ref}}
      - name: If on specific branch set a different value
        if: github.ref == 'refs/heads/demo'
        run: |
          echo "::set-env name=VALUE::bah"
      - name: echo var
        run: echo $VALUE
